from picamera import PiCamera
import time
from gpiozero import LED
from gpiozero import Buzzer

greenLED = LED(2)
redLED = LED(3)
greenLED.off()
redLED.off()
buzz = Buzzer(21)
buzz.off()
userInterface = input('What do you want to do with the camera? CP or CV or None: ')
camera = PiCamera()
time.sleep(2)


if userInterface == 'cp':
    camera.vflip = True
    camera.start_preview()
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    time.sleep(0.3)
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    time.sleep(0.3)
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    camera.capture('/home/pi/Desktop/img.jpg', 0)
    camera.stop_preview()
    print('Image captured. Check Desktop folder.')
    greenLED.on()
    buzz.on()
    time.sleep(1)
    buzz.off()
    time.sleep(1)
    greenLED.off()
elif userInterface == 'cv':
    duration = input('How long would you like your video in seconds? ')
    camera.vflip = True
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    time.sleep(0.3)
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    time.sleep(0.3)
    redLED.on()
    time.sleep(0.3)
    redLED.off()
    print('Recording started...')
    time.sleep(0.5)
    camera.start_preview()
    camera.start_recording('/home/pi/Desktop/vid.h264')
    camera.wait_recording(int(duration))
    camera.stop_preview()
    camera.stop_recording()
    print('Video captured. Check Desktop folder.')
    greenLED.on()
    buzz.on()
    time.sleep(1)
    buzz.off()
    time.sleep(1)
    greenLED.off()
else:
    print('Choose CP or death.')
